Fixes https://github.com/qdouble/angular-webpack2-starter/issues/264
Summary:

package.json: Fixes jasmine dev dependencies as stated here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14569#issuecomment-279306281

tsconfig.*.json

es7 required to solve the following issues

ERROR in [at-loader] src/app/app.component.ts:14:25
    TS2339: Property 'includes' does not exist on type 'string[]'.

ERROR in [at-loader] src/app/app.imports.ts:19:23
    TS2339: Property 'includes' does not exist on type 'string[]'.

ERROR in [at-loader] src/app/features/store-devtools.module.ts:11:23
    TS2339: Property 'includes' does not exist on type 'string[]'.

ERROR in [at-loader] node_modules/@angular/core/typings/src/facade/lang.d.ts:11:17
    TS2693: 'Map' only refers to a type, but is being used as a value here.

ERROR in [at-loader] node_modules/@angular/core/typings/src/facade/lang.d.ts:12:17
    TS2693: 'Set' only refers to a type, but is being used as a value here.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:350:48
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:351:52
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:352:34
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:353:34
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:354:34
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:355:61
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:356:60
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:357:65
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:357:97
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:358:60
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:359:58
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:360:59
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:361:58
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:362:61
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:362:117
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:363:42
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:365:81
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:366:78
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:367:76
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:368:73
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:464:59
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:465:59
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:467:48
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:468:69
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:472:40
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:474:48
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:494:55
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:495:45
    TS2304: Cannot find name 'PropertyKey'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:627:18
    TS2304: Cannot find name 'PromiseConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:1280:34
    TS2339: Property 'for' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:1284:41
    TS2339: Property 'hasInstance' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:1288:48
    TS2339: Property 'isConcatSpreadable' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:1296:36
    TS2339: Property 'keyFor' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:1300:35
    TS2339: Property 'match' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:1304:37
    TS2339: Property 'replace' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:1308:36
    TS2339: Property 'search' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:1312:37
    TS2339: Property 'species' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:1316:35
    TS2339: Property 'split' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:1320:41
    TS2339: Property 'toPrimitive' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:1324:41
    TS2339: Property 'toStringTag' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:1328:41
    TS2339: Property 'unscopables' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:2059:34
    TS2339: Property 'for' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:2063:41
    TS2339: Property 'hasInstance' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:2067:48
    TS2339: Property 'isConcatSpreadable' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:2075:36
    TS2339: Property 'keyFor' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:2079:35
    TS2339: Property 'match' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:2083:37
    TS2339: Property 'replace' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:2087:36
    TS2339: Property 'search' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:2091:37
    TS2339: Property 'species' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:2095:35
    TS2339: Property 'split' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:2099:41
    TS2339: Property 'toPrimitive' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:2103:41
    TS2339: Property 'toStringTag' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/@types/core-js/index.d.ts:2107:41
    TS2339: Property 'unscopables' does not exist on type 'SymbolConstructor'.

ERROR in [at-loader] node_modules/rxjs/Observable.d.ts:69:60
    TS2693: 'Promise' only refers to a type, but is being used as a value here.

ERROR in [at-loader] webpack.config.ts:91:38
    TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.

ERROR in [at-loader] webpack.config.ts:239:12
    TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.

ERROR in [at-loader] node_modules/@types/jasmine/index.d.ts:39:52
    TS1005: '=' expected.

ERROR in [at-loader] node_modules/@types/jasmine/index.d.ts:41:62
    TS1005: '=' expected.

ERROR in [at-loader] node_modules/@types/jasmine/index.d.ts:39:38
    TS2371: A parameter initializer is only allowed in a function or constructor implementation.

ERROR in [at-loader] node_modules/@types/jasmine/index.d.ts:39:46
    TS2304: Cannot find name 'keyof'.

ERROR in [at-loader] node_modules/@types/jasmine/index.d.ts:41:46
    TS2371: A parameter initializer is only allowed in a function or constructor implementation.

ERROR in [at-loader] node_modules/@types/jasmine/index.d.ts:41:56
    TS2304: Cannot find name 'keyof'.